### ISSUE TITLE
The scope of the variable 'isNegative' can be reduced.

### ISSUE THREAD

**Issue by lvntky** [lvntky/ArtilleryOS#38]
This change can be made to improve code quality. The following error was encountered in the static analysis performed on the code:
`kernel/src/qemu_debug.c:39:6: style: The scope of the variable 'isNegative' can be reduced. [variableScope]
 int isNegative = 0;`

When I checked the code, I realized that we don't actually need this variable.

the relevant method can be updated as follows:
```
void itoa_dbg(int n, char *buffer, int base)
{
    int i = 0;

    // Handle 0 explicitly, otherwise an empty string is printed
    if (n == 0) {
        buffer[i++] = '0';
        buffer[i] = '\0';
    } else {
        // Handle negative numbers only if the base is 10
        if (n < 0 && base == 10) {
            n = -n;

            // Append negative sign for base 10
            buffer[i++] = '-';
        }

        // Process individual digits
        while (n != 0) {
            int rem = n % base;
            buffer[i++] = (rem > 9) ? (rem - 10) + 'a' : rem + '0';
            n = n / base;
        }

        buffer[i] = '\0'; // Null-terminate the string
    }

    // Reverse the string
    int start = 0;
    int end = i - 1;
    while (start < end) {
        // Swap characters
        char temp = buffer[start];
        buffer[start] = buffer[end];
        buffer[end] = temp;
        start++;
        end--;
    }
}
```
I haven't tested it but theoratically it will work :) the implementation and test is required. You can use the following function or re-implement your own itoa. 

PS: the "_debug" endfix just used for telling this function only used on debug purpuses. nothing else.

**Comment by lvntky** [comment]
@angelpilled do you want to take this one?

**Comment by angelpilled** [comment]
> @angelpilled do you want to take this one?

Yessir.

**Comment by lvntky** [comment]
> > @angelpilled do you want to take this one?
> 
> Yessir.

Alright, i assigned it to you !
