### ISSUE TITLE
implement <string.h> functions

### ISSUE THREAD

**Issue by moussacodes** [lvntky/ArtilleryOS#47]
Currently, only the following functions are implemented:

void *memset(void *, int, size_t);
void *memcpy(void *, const void *, size_t);
void *memmove(void *, const void *, size_t);
int strcmp(char *, char *str2);

I intend to implement the remaining functions:
strlen, strcpy, strncpy, strcat, strncat, strncmp, strtok.

**Comment by lvntky** [comment]
that would be fantastic! I can assign this issue to you if you want it @moussacodes

**Comment by moussacodes** [comment]
That would be great
