### ISSUE TITLE
Double printing is not working as intended

### ISSUE THREAD

**Issue by angelpilled** [lvntky/ArtilleryOS#53]
While I was testing my double math functions, I noticed that doubles get printed in the reverse order. For example, I'm expecting to see 0.5000, but it prints out 0005.0

**Comment by lvntky** [comment]
i dont think this occured the state of the kernel or cpu but how we represent the double variables in printf. I can assign this issue to you if you want to for further debuging

**Comment by angelpilled** [comment]
I could take it, but I might not be able to resolve. Anyways, assign it to me. I'll check tomorrow.

**Comment by moussacodes** [comment]
the reason is the [line 68](https://github.com/lvntky/ArtilleryOS/blob/master/kernel/libc/stdio.c)

**Comment by angelpilled** [comment]
Thank you @moussacodes, I'll fix it right away (if this won't cause any issues)

**Comment by angelpilled** [comment]
> the reason is the [line 68](https://github.com/lvntky/ArtilleryOS/blob/master/kernel/libc/stdio.c)
Should be fixed in PR #55
